import PageClient from "./PageClient";

export const dynamic = "force-static";

export function generateStaticParams() {
  return [{ slug: "kajaria-glazed-vitrified-white-marble" }, { slug: "somany-anti-skid-bathroom-tile" }, { slug: "kajaria-outdoor-parking-tile" }, { slug: "somany-digital-wood-plank-tile" }, { slug: "kajaria-polished-marble-600x600" }, { slug: "somany-wall-tile-glossy-white" }, { slug: "kajaria-porcelain-grey-800x800" }, { slug: "nitco-mosaic-accent-tile" }, { slug: "jaquar-lyric-overhead-shower" }, { slug: "hindware-neo-wash-basin" }, { slug: "jaquar-aria-single-lever-faucet" }, { slug: "cera-primo-wall-hung-basin" }, { slug: "jaquar-continental-bathtub" }, { slug: "hindware-towel-rail-chrome" }, { slug: "cera-opus-shower-panel" }, { slug: "jaquar-eon-health-faucet" }, { slug: "ultratech-opc-53-grade-cement" }, { slug: "jk-cement-ppc" }, { slug: "ultratech-white-cement" }, { slug: "jk-wall-putty" }, { slug: "tata-tiscon-tmt-bar-12mm" }, { slug: "tata-tiscon-tmt-bar-8mm" }, { slug: "jsw-tmt-bar-16mm" }, { slug: "binding-wire-20-gauge" }, { slug: "asian-paints-royale-luxury-emulsion" }, { slug: "berger-weather-coat-exterior" }, { slug: "asian-paints-interior-primer" }, { slug: "nerolac-excel-exterior-anti-fungal" }, { slug: "asian-paints-texture-sand" }, { slug: "berger-easy-clean-kitchen-paint" }, { slug: "havells-hr-frls-wire-2-5sqmm" }, { slug: "legrand-arteor-modular-switch" }, { slug: "schneider-acti9-mcb-32a" }, { slug: "havells-ceiling-fan-36inch" }, { slug: "astral-cpvc-pipe-half-inch" }, { slug: "finolex-upvc-column-pipe" }, { slug: "astral-ball-valve-half-inch" }, { slug: "sintex-water-tank-1000l" }, { slug: "philips-led-panel-18w" }, { slug: "wipro-led-strip-light-5m" }, { slug: "havells-gx53-led-downlight" }, { slug: "philips-outdoor-bollard-light" }, { slug: "cera-floor-mounted-ewc" }, { slug: "hindware-wall-hung-rimless-wc" }, { slug: "jaquar-concealed-cistern" }, { slug: "cera-wash-basin-pedestal" }, { slug: "dr-fixit-waterproofing-liquid" }, { slug: "laticrete-tile-adhesive-c2-grade" }, { slug: "saint-gobain-gyproc-gypsum-board" }, { slug: "greenply-bwd-plywood-18mm" }];
}

export default function Page(props: { params: Promise<{ slug: string }> }) {
  return <PageClient {...props} />;
}
